### ISSUE TITLE
STFU OPERATOR DETECTED

### ISSUE THREAD

**Issue by efik** [rascada/Pogoda#24]
[session.php](https://github.com/rascada/Pogoda/blob/master/session.php#L5) 
@ należy zlikwidować i nigdy więcej jej nie używać :+1: 

Pull #25

**Comment by efik** [comment]
@marcinlacina hihi :D

**Comment by rascada** [comment]
Ten kod jest straszny, nawet na niego nie patrz :D
Ale niedługo będzie przepisany :P

**Comment by marcinlacina** [comment]
Niedługo xd

**Comment by rascada** [comment]
hahaha :D

**Comment by efik** [comment]
Przepiszcie na symfony ( ͡° ͜ʖ ͡°)
haha :D Pozdrowienia.

**Comment by rascada** [comment]
Najlepiej na node.js
