### ISSUE TITLE
api jsonp support

### ISSUE THREAD

**Issue by rascada** [rascada/Pogoda#31]
- pierwszy pomysł to podanie parametru `json` w zmiennej getowej, ten pomysl wydaje sie byc najlepszy :p

**Comment by syntaxerro** [comment]
a2c960a966c3c47a8d417fcc41780687d0df7de3
A jednak rozszerzenie. Ze względu, że cały getowy query-bag ma już inne wykorzystanie.

**Comment by syntaxerro** [comment]
af049a0bd381680758ce39deec336c060451b1ac

**Comment by rascada** [comment]
![image](https://cloud.githubusercontent.com/assets/10521222/11820074/cfd78432-a362-11e5-8fff-ced0d447a283.png)
