### ISSUE TITLE
cors for api

### ISSUE THREAD

**Issue by rascada** [rascada/Pogoda#33]

**Comment by syntaxerro** [comment]
Jak git to zamknij.

**Comment by rascada** [comment]
Bez rozszerzenia (*/basic`.json`) z nagłówkiem xrw też jest?

**Comment by syntaxerro** [comment]
nie, po co?

**Comment by rascada** [comment]
To mozesz? 
Jak będzie tam cors to już to rozszerzenie jest zdaje się nie potrzebne :P
Ale niech zostanie, i dopisz do api że wspiera jsonp :D

**Comment by rascada** [comment]
A, github ogarnia wiadomości realtime :P

**Comment by syntaxerro** [comment]
Jest potrzebne, bo dostaniesz htmla z viewerem bez rozszerzenia. I średnio mi się podoba dawać tam ten nagłówek.

**Comment by rascada** [comment]
Nie czaje :d 
Chcę zrobić ajaxa z nagłowkiem x-requested-with ale jest cross-domain

**Comment by syntaxerro** [comment]
Aaa, nie no nie. Już niech zostanie jak jest. Mi się podoba nawet bardziej tak niż po nagłówku.

**Comment by rascada** [comment]
wywaliles ten naglowek xd
dla mnie to właśnie był sztos, :D 
ale luz
