### ISSUE TITLE
XHR basic.json wpada w pętle bez żadnego timeouta.

### ISSUE THREAD

**Issue by syntaxerro** [rascada/Pogoda#35]
![zrzut ekranu z 2015-12-16 22 32 42](https://cloud.githubusercontent.com/assets/10521497/11854604/2de0d76c-a445-11e5-9022-a438b0755081.png)

**Comment by rascada** [comment]
miał 100ms timeouta :P

**Comment by syntaxerro** [comment]
:+1:
