### ISSUE TITLE
api forecast.json not allowed access

### ISSUE THREAD

**Issue by rascada** [rascada/Pogoda#44]
No 'Access-Control-Allow-Origin'

**Comment by syntaxerro** [comment]
![zrzut ekranu z 2015-12-20 17 33 09](https://cloud.githubusercontent.com/assets/10521497/11918793/dd720460-a73f-11e5-8eb5-7f03c7784ae5.png)

**Comment by rascada** [comment]
`//` i łączyło z syntax-shell po http xd
btw na localu mam 500 bo nie mam klasy redis'a, a nie chce mi się update'ować php'a :P
