### ISSUE TITLE
pogoda hooks

### ISSUE THREAD

**Issue by rascada** [rascada/Pogoda#45]
![image](https://cloud.githubusercontent.com/assets/10521222/11919292/bccc8668-a74e-11e5-9038-5d48706fc090.png)

![image](https://cloud.githubusercontent.com/assets/10521222/11919297/d81e1f9e-a74e-11e5-8437-2bb30097e0ec.png)

**Comment by syntaxerro** [comment]
Puść po sslu.

**Comment by rascada** [comment]
![image](https://cloud.githubusercontent.com/assets/10521222/11919371/358d62e6-a751-11e5-8aac-f930a8eddcf6.png)

**Comment by syntaxerro** [comment]
Dobra to czekaj zrobię wyjątek dla hooksa (bez 301), a Ty przepnij z powrotem na normalne http.

**Comment by rascada** [comment]
Github pozwolił wyłączyć sprawdzanie ssl'a
![image](https://cloud.githubusercontent.com/assets/10521222/11919382/72f0c83a-a751-11e5-8d9c-7cc5fb8c8321.png)

**Comment by syntaxerro** [comment]
Gitez. :+1:
