### ISSUE TITLE
Przy kolejnych requestach termometr nie żyje.

### ISSUE THREAD

**Issue by syntaxerro** [rascada/Pogoda#50]
![zrzut ekranu z 2015-12-23 11 21 17](https://cloud.githubusercontent.com/assets/10521497/11974765/7fdc340e-a967-11e5-9a0b-c3264348b36f.png)
Zostawiłem na ponad godzinę kompa z otwartym prod. Przychodzę i dalej ta sama temperatura. 
Poczekałem do następnego requesta i zobaczyło to: przyleciało 12.08 a na termometrze dalej 8.6.

**Comment by rascada** [comment]
basic api class - #52

**Comment by rascada** [comment]
jak chce testować to temperatura: `11.1`, `11.1`, `11.1`,`...` 7 razy z rzędu xd

**Comment by syntaxerro** [comment]
Jest git. Działa. :+1:
