### ISSUE TITLE
Too long forecast title

### ISSUE THREAD

**Issue by rascada** [rascada/Pogoda#67]
Jednak nie wszystkie ikonki się różnią (dzień/noc)

![image](https://cloud.githubusercontent.com/assets/10521222/12100434/3c49a3c6-b32f-11e5-943e-268b56d5a140.png)
![image](https://cloud.githubusercontent.com/assets/10521222/12100437/41a6e6c6-b32f-11e5-9965-c30577cbd2e2.png)

**Comment by syntaxerro** [comment]
Fuck. xd A dasz radę dzień i noc na raz pokazać?

**Comment by rascada** [comment]
Tak właśnie będę kminił. A jak się nie wyrobię do milestone'a to wytnę tylko "wieczór" i zostanie sama "noc"

**Comment by rascada** [comment]
Ej, czemu w pogodzie dla nocy i dla dnia jest "rano śnieg"? xd

**Comment by syntaxerro** [comment]
Pytaj się tych z wu. xd
