### ISSUE TITLE
Invalid wind dir data.

### ISSUE THREAD

**Issue by syntaxerro** [rascada/Pogoda#79]
![zrzut ekranu z 2016-01-24 10 38 15](https://cloud.githubusercontent.com/assets/10521497/12535528/cc4f2a48-c286-11e5-86d6-fdef9e2a93e3.png)

WTF? z 205 deg zrobiło się 25?

**Comment by rascada** [comment]
A strzałka nie powinna wskazywać w którą stronę wieje wiatr, zamiast skąd?

**Comment by syntaxerro** [comment]
Aaa, bo Ty obróciłeś o 180deg. W sumie nie wiem, wg. wiki powinno się podawać kierunek, z którego wieje. Ale z drugiej strony w ten sposób wygląda lepiej. Może wskaźnik zostaw tak jak jest, ale napis z cyferką niech będzie z oryginalną wartością? Bo trochę dziwnie się patrzy na `25deg` i obok napis `z południa`.
