### ISSUE TITLE
Ogarnij żeby kolorek tła barometra zmieniał się tak jak tendencja. Tak samo jak jest przy tendencji temperatury

### ISSUE THREAD

**Issue by syntaxerro** [rascada/Pogoda#9]

**Comment by rascada** [comment]
Nie dałeś żadnego labela do issues xd 
Całe? Może ogarnę jakąś kropeczkę na nich?

**Comment by syntaxerro** [comment]
no może być kropeczka xd byle by jakoś było fajnie

**Comment by rascada** [comment]
Powiedz mi gdzie jest tendencja barometra :d

**Comment by rascada** [comment]
Już :P
